export default actionTypes = {
    ///////////////// Authentication ///////////////////////
    SIGNUP_PROGRESS: "SIGNUP_PROGRESS",
    SIGNUP_SUCCEED: "SIGNUP_SUCCEED",
    SIGNUP_ERROR: "SIGNUP_ERROR",
    SIGNUP_ERROR_ALERT: "SIGNUP_ERROR_ALERT",
    SIGNIN_PROGRESS: "SIGNIN_PROGRESS",
    SIGNIN_SUCCEED: "SIGNIN_SUCCEED",
    SIGNIN_ERROR: "SIGNIN_ERROR",
    SIGNIN_ERROR_ALERT: "SIGNIN_ERROR_ALERT",
    ///////////////// Authentication ///////////////////////

    //////////////////////App ////////////////////////////
    SERVICE_PROGRESS: "SERVICE_PROGRESS",
    SERVICE_SUCCESS: "SERVICE_SUCCESS",
    SERVICE_ERROR: 'SERVICE_ERROR',
    SERVICE_ERROR_ALERT: 'SERVICE_ERROR_ALERT',


    //////////////////////PAyment ////////////////////////////

    PAYMENT_PROGRESS: "PAYMENT_PROGRESS",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_ERROR: "PAYMENT_ERROR",
    PAYMENT_ERROR_ALERT: "PAYMENT_ERROR_ALERT",





    ////////////////get user /////////////////

    GET_USER_SINGUP_PROGRESS: "GET_USER_SINGUP_PROGRESS",
    GET_USER_SINGUP_SUCCESS: "GET_USER_SINGUP_SUCCESS",



    /////////////////////////contact////////////////////

    CONTACT_PROGRESS: 'CONTACT_PROGRESS',
    CONTACT_SUCCESS: 'CONTACT_SUCCESS',
    CONTACT_ERROR: 'CONTACT_ERROR',
    CONTACT_ERROR_LIST: 'CONTACT_ERROR_LIST',



    //////////////////////Notification ////////////////////////////

    GET_NOTIFICATION_PROGRESS: "GET_NOTIFICATION_PROGRESS",
    GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",

    //////////////////////Notification ////////////////////////////
    GET_Bill_PROGRESS: "GET_Bill_PROGRESS",
    GET_Bill_SUCCESS: "GET_Bill_SUCCESS",

    //////////////////////utility payment///////////////

    UTILITY_PAYMENT_PROGRESS: "UTILITY_PAYMENT_PROGRESS",
    UTILITY_PAYMENT_SUCCESS: "UTILITY_PAYMENT_SUCCESS",

    GET_PROPERTY_ONE_BED_PROGRESS: "GET_PROPERTY_ONE_BED_PROGRESS",
    GET_PROPERTY_ONE_BED_SUCCESS: 'GET_PROPERTY_ONE_BED_SUCCESS',
    GET_PROPERTY_TWO_BED_SUCCESS: 'GET_PROPERTY_TWO_BED_SUCCESS',
    GET_PROPERTY_TWO_BED_PROGRESS: 'GET_PROPERTY_TWO_BED_PROGRES',
    GET_PROPERTY_THREE_BED_SUCCESS: 'GET_PROPERTY_THREE_BED_SUCCESS',
    GET_PROPERTY_THREE_BED_PROGRESS: 'GET_PROPERTY_THREE_BED_PROGRESS'




}